Create test/window directory and conftest file
twosigma/pandas pull request #3
Opened 2019-07-08 06:12 UTC by mroeschke

Precursor to https://github.com/twosigma/pandas/pull/2

2019-07-08 11:53 UTC, jreback requested changes
I would do this versus pandas/master. Best to push whatever we can there in small uncontroversial bits.

2019-07-08 11:53 UTC, jreback commented on pandas/tests/window/conftest.py
> +)
can you add a 1-line comment on each of these

2019-07-08 16:41 UTC, mroeschke commented
Sounds good. I'll open this PR up against pandas/master instead.

2019-07-08 16:41 UTC, closed without merging

2019-07-09 07:27 UTC, mroeschke commented
Created https://github.com/pandas-dev/pandas/pull/27305 with the first cleanup