Add POC document
twosigma/pandas pull request #33
Opened 2019-10-02 07:33 UTC by mroeschke

- [ ] closes #xxxx

2019-10-02 18:59 UTC, mroeschke commented
A quick performance consideration this doesn't include:

* The current `VariableWindowIndexer` and `FixedWindowIndexer` are still using `jitclass` and the performance hit is especially bad for offset rolling. I will put up another PR for this change as local testing showed I can get another 2x performance boost for rolling mean.

2019-10-02 21:28 UTC, DiegoAlbertoTorres commented on doc/source/development/rolling_operations_with_numba.rst
> +Additionally this POC includes an API that allows users to create custom window boundary calculations.
Let's add a section where we give a concrete proposal for shipping these changes: in Pandas 1.0 (and add link to the roadmap), with Numba as a hard dependency, etc.

2019-10-02 21:29 UTC, DiegoAlbertoTorres commented on doc/source/development/rolling_operations_with_numba.rst
> +Additionally this POC includes an API that allows users to create custom window boundary calculations.
Also mention docs and todos

2019-10-02 21:30 UTC, DiegoAlbertoTorres commented on doc/source/development/rolling_operations_with_numba.rst
> +   In [3]: n = 1_000_000
Let's try these with 10M, 100M and 1B

2019-10-03 09:58 UTC, jreback commented on doc/source/development/rolling_operations_with_numba.rst
> +
let’s add a Future section
- use jitclasses (mention issues and resolution: https://github.com/numba/numba/issues/4522#issuecomment-537872456)

can include what we want short term (implement rest of the aggregations, expanding, ewma)

and longer term; groupby & groupby + rolling

2019-10-08 06:02 UTC, mroeschke commented on doc/source/development/rolling_operations_with_numba.rst
> +   In [3]: n = 1_000_000
For memory, which we were most curious about, at 1B the Numba implimentation is finally starting to edge out Cython. Does that align with your experience?

```
# POC
In [1]: %load_ext memory_profiler

In [2]: n = 1_000_000_000

In [3]: roll_fixed = pd.Series(range(n)).rolling(10)

In [4]: %memit roll_fixed.apply(lambda x: np.sum(x) + 5, raw=True)
peak memory: 11747.92 MiB, increment: 4056.36 MiB

# master
In [1]: %load_ext memory_profiler

In [2]: n = 1_000_000_000

In [3]: roll_fixed = pd.Series(range(n)).rolling(10)

In [4]: %memit roll_fixed.apply(lambda x: np.sum(x) + 5, raw=True)
peak memory: 12581.71 MiB, increment: 4860.52 MiB
```

2019-10-09 19:31 UTC, DiegoAlbertoTorres commented on doc/source/development/rolling_operations_with_numba.rst
> +a ``BaseIndexer`` class is available from ``pandas/core/window/indexers.py`` for users to subclass
s/is available from/in

2019-10-09 19:32 UTC, DiegoAlbertoTorres commented on doc/source/development/rolling_operations_with_numba.rst
> +Below is an example of creating an ``ExpandingIndexer`` computes an expanding window similar to
s/computes/that computes

2019-10-09 19:32 UTC, DiegoAlbertoTorres commented on doc/source/development/rolling_operations_with_numba.rst
> +Below is table comparing the current performance difference between the Numba and Cython implementations
s/is/is a

2019-10-09 19:36 UTC, DiegoAlbertoTorres commented on doc/source/development/rolling_operations_with_numba.rst
> +   In [3]: n = 1_000_000
Interesting. I think it is possible that rolling in Cython is just pretty efficient. The time I got a significant memory improvement over Pandas was comparing with a Numba EWA implementation, which is definitely more complex.

2019-10-09 19:37 UTC, DiegoAlbertoTorres commented on doc/source/development/rolling_operations_with_numba.rst
> +   In [3]: n = 1_000_000
I think it is worth mentioning somewhere in the doc that we have already found that, as N increases, the memory difference decreases and eventually Numba beats the existing impl.

2019-10-10 11:47 UTC, jreback requested changes
looks good, some small changes

2019-10-10 11:47 UTC, jreback commented on doc/source/development/rolling_operations_with_numba.rst
> +Rolling Operations with Numba
Pandas Window Operations Refactor

2019-10-10 11:47 UTC, jreback commented on doc/source/development/rolling_operations_with_numba.rst
> +``rolling.mean`` and ``rolling.apply`` utilizes ``njit`` functions to separately calculate:
can you put a reference to njit here from the numba docs

2019-10-10 11:47 UTC, jreback commented on doc/source/development/rolling_operations_with_numba.rst
> +Additionally this POC includes an new API that allows users to create custom window boundary calculations
Add a sentence explaining *why* we would want to create custom window boundaries. this allows the user to easily overide window calculcations, for example to account for holidays or missing periods, w/o requiring changes in pandas itself.

2019-10-10 11:47 UTC, jreback commented on doc/source/development/rolling_operations_with_numba.rst
> +we would like to introduce ``Numba`` as a required dependency for pandas in the 1.0 release
comma after release

2019-10-10 11:47 UTC, jreback commented on doc/source/development/rolling_operations_with_numba.rst
> +and have the ``rolling.mean`` and ``rolling.apply`` operations use ``Numba`` instead of ``Cython`` in the release.
can you reference these in the pandas docs themselves (use a full link)

2019-10-10 11:47 UTC, jreback commented on doc/source/development/rolling_operations_with_numba.rst
> +to compute ``rolling.mean`` and ``rolling.apply`` without introducing any user facing API changes.
use the full refernce here (i left a comment about this below, but here is enough)

2019-10-10 11:47 UTC, jreback commented on doc/source/development/rolling_operations_with_numba.rst
> +The design document for this implementation can be found in :doc:`generalized_window`
use the full reference here (the github link)

2019-10-10 11:47 UTC, jreback commented on doc/source/development/rolling_operations_with_numba.rst
> +   from pandas.core.window.indexers import BaseIndexer
create a separate issue, we may want to expose the name in pandas.api.indexers (BaseIndexer) for user consumption.

2019-10-10 16:02 UTC, mroeschke commented on doc/source/development/rolling_operations_with_numba.rst
> +   In [3]: n = 1_000_000
Sounds good. Noted the long term memory pattern

2019-10-14 03:38 UTC, mroeschke commented
Will merge this in Monday evening and write the corresponding pandas issue + mailing list. If there are no further comments.

2019-10-14 12:05 UTC, jreback approved these changes
lgtm minor comments

2019-10-14 12:05 UTC, jreback commented on doc/source/development/rolling_operations_with_numba.rst
> +of Two Sigma's pandas repo.
you don’t need to mention two sigma explicitly ; just point to the repo

2019-10-14 12:05 UTC, jreback commented on doc/source/development/rolling_operations_with_numba.rst
> +           return np.zeros(num_values, dtype=np.int64), np.arange(1, num_values + 1)
use int32

2019-10-15 05:03 UTC, merged